# Generated by Django 5.0.2 on 2024-02-27 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('ID_VENDEDOR', models.AutoField(primary_key=True, serialize=False)),
                ('CODIGO', models.CharField(max_length=10, null=True, unique=True)),
                ('NOMBRE', models.CharField(max_length=100)),
                ('ACTIVO', models.BooleanField(default=True)),
                ('RETIRADO', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_CLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('RUC', models.CharField(max_length=11, unique=True)),
                ('RAZON_SOCIAL', models.CharField(max_length=100)),
                ('TIPO_CLIENTE', models.IntegerField(choices=[(1, 'Cliente final'), (2, 'Subdistribuidor')], null=True)),
                ('GRUPO_ECON', models.CharField(default='999', max_length=3)),
                ('NOMBRE_GRUPO', models.CharField(blank=True, max_length=100, null=True)),
                ('VENDEDOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('IT', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.IntegerField(choices=[(1, 'Factura'), (2, 'Boleta'), (3, 'Nota de crédito'), (4, 'Nota de débito'), (5, 'Otro')], null=True)),
                ('DCTO_N', models.CharField(max_length=20, unique=True)),
                ('MONEDA', models.CharField(choices=[('S/', 'Soles'), ('USD', 'Dólares')], default='S/', max_length=3)),
                ('IMPORTE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PLAZO', models.IntegerField()),
                ('FECHA_EMISION', models.DateField()),
                ('RECEP_FT', models.DateField()),
                ('FECHA_VENCIMIENTO', models.DateField(blank=True, null=True)),
                ('CANCELADO', models.BooleanField(default=False)),
                ('ANULADO', models.BooleanField(default=False)),
                ('OBSERVACION', models.TextField(blank=True, null=True)),
                ('FECHA_PAGO', models.DateField(blank=True, null=True)),
                ('MODO_PAGO', models.CharField(blank=True, choices=[('CHE', 'CHEQUE'), ('LE', 'LETRA'), ('FCT', 'FACTORING'), ('TI', 'TRANSACCION INTERBANCARIA'), ('DFN', 'DESCUENTO DE FACTURA NEGOCIABLE'), ('EFE', 'EFECTIVO')], max_length=3, null=True)),
                ('COMISIONADO', models.BooleanField(default=False)),
                ('NUMERO_OPERACION', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
    ]
