# Generated by Django 5.0.2 on 2024-03-01 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_historicalcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRazonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social_anterior', models.CharField(max_length=100)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_razon_social', to='ventas.cliente')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
