# Generated by Django 5.0.2 on 2024-03-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_historialrazonsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='razones_sociales_anteriores',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='razones_sociales_anteriores',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
