# Generated by Django 5.0.2 on 2024-03-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_cliente_razones_sociales_anteriores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='MODO_PAGO',
            field=models.CharField(blank=True, choices=[('CHE', 'CHEQUE'), ('LE', 'LETRA'), ('FCT', 'FACTORING'), ('TI', 'TRANSACCION INTERBANCARIA'), ('DFN', 'DESCUENTO DE FACTURA NEGOCIABLE'), ('EFE', 'EFECTIVO')], max_length=10, null=True),
        ),
    ]
