# Generated by Django 5.0.2 on 2024-03-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_venta_modo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='DCTO_N',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('DCTO_N', 'tipo_documento')},
        ),
    ]
