# Generated by Django 5.0.2 on 2024-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_dcto_n_alter_venta_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FECHA_EMISION',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='PLAZO',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='RECEP_FT',
            field=models.DateField(null=True),
        ),
    ]
