# Generated by Django 5.0.2 on 2024-03-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.IntegerField(choices=[(1, 'Factura'), (2, 'Boleta'), (3, 'Nota de crédito'), (4, 'Nota de débito'), (5, 'Otro')])),
                ('DCTO_N', models.CharField(max_length=20)),
                ('MONEDA', models.CharField(choices=[('S/', 'Soles'), ('USD', 'Dólares')], default='S/', max_length=3)),
                ('IMPORTE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PLAZO', models.IntegerField(null=True)),
                ('FECHA_EMISION', models.DateField(null=True)),
                ('RECEP_FT', models.DateField(null=True)),
                ('FECHA_VENCIMIENTO', models.DateField(blank=True, null=True)),
                ('CANCELADO', models.BooleanField(default=False)),
                ('ANULADO', models.BooleanField(default=False)),
                ('OBSERVACION', models.TextField(blank=True, null=True)),
                ('FECHA_PAGO', models.DateField(blank=True, null=True)),
                ('MODO_PAGO', models.CharField(blank=True, choices=[('CHE', 'CHEQUE'), ('LE', 'LETRA'), ('FCT', 'FACTORING'), ('TI', 'TRANSACCION INTERBANCARIA'), ('DFN', 'DESCUENTO DE FACTURA NEGOCIABLE'), ('EFE', 'EFECTIVO')], max_length=10, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
        ),
    ]
