# Generated by Django 5.0.2 on 2024-06-12 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_cuota_proveedor_alter_cuota_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='numero_cuota',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Emisión'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Importe Total'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='moneda',
            field=models.CharField(max_length=3, null=True, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='numero_documento',
            field=models.CharField(max_length=20, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='numero_unico',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Número Único'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='plazo',
            field=models.IntegerField(null=True, verbose_name='Plazo en días'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='MODO_PAGO',
            field=models.CharField(blank=True, choices=[('CHE', 'CHEQUE'), ('LE', 'LETRA'), ('FCT', 'FACTORING'), ('TI', 'TRANSACCION INTERBANCARIA'), ('DFN', 'DE SCUENTO DE FACTURA NEGOCIABLE'), ('EFE', 'EFECTIVO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='importe_cuota',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe de la Cuota'),
        ),
    ]
