# Generated by Django 5.0.2 on 2024-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_remove_cuota_codigo_remove_cuota_numero_cuota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='importe_total',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='numero_documento',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='numero_unico',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número Único'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='plazo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo en días'),
        ),
    ]
